name: urban-technologies-berlin
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7
  - pip
  - numpy
  - pandas
  - geopandas
  - tqdm
  - beautifulsoup4
  - colour
  - matplotlib
  - descartes
  - contextily
  - pillow
  - pip:
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:
     - sphinx-rtd-theme
     - berlin-opendata-downloader
  # for development only (could also be kept in a separate environment file)
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
  - click
